### ISSUE TITLE
Events might collide

### ISSUE THREAD

**Issue by alshakero** [Palindrom/palindrom-connection#1]
I finished implementing the component and quite excited about it. But I discovered and little obstacle on the way:

Dispatching events to `window` turns out to be a potentially bad idea, it would kill the ability to have a blending of two Palindrom apps on the same `window`. For example, if `patch-applied` was dispatched, subscribers won't be able to tell whether it concerns them or other apps. My current working and tested solution is to prefix all the event names with a custom prefix passable by an attribute `event-prefix`. I also warn with a nice message when two instances of `palindrom-connection` exist and no prefix is set. The warning is this:
```
It seems like you have more than one <palindrom-connection/> instances in your document. This could lead to events collision without event-prefix attribute. Please prefix your event-names by setting `event-prefix` attribute, eg: `<palindrom-connection event-prefix="your-custom-prefix" />` and use the same prefix when subscribing to the events.
```
Obviously, `<palindrom-polymer />` and `<palindrom-react />` would accept the same attribute to prefix their listeners.

I like this solution a lot because it makes development easier for the most common case (single p-c instance). And warns nicely for the uncommon cases. 

There is another solution that might be worth discussing, which is disabling event bubbling. This one is cleaner a little bit. But will need the other element to have an attribute called (in effect) `palindrom-connection-element-id`, so the other element could find `palindrom-connection` and subscribe to its events without any of them polluting `window`.

I obviously lean to the first one, because I've written it and even written tests for the warnings. 

There can be other solutions, you're more than welcome to suggest any.

Tell me your thoughts @warpech @tomalec

**Comment by tomalec** [comment]
I think the common approach to colliding event names for events that bubbles is to use `event.target` you can either setup a listener on exact element, like 
```js
document.querySelector('palindrom-connection.app-1').addEventListener('patch-applied',/*doSomething*/)
```
 or if you are listening on `window`
```js
window.addEventListener('patch-applied', function(event){
    if(event.target.id === 'app-1'){
        // doSomething(event);
    }
});
```

I would not expect `<button>` to consume `event-prefix` attribute to emit `event-prefix-click`, `event-prefix-mouseup` etc. You listen on `window` or `document.body` for an event (like `click`) to do gather all.

**Comment by alshakero** [comment]
If we are to set listeners to the exact element why don't we just disable bubbling to scope the events?

**Comment by tomalec** [comment]
Because sometimes you may like it:

```html
<h2>Check Polymer and Vue apps working side by side</h2>
<my-polymer-app><!-- this is where you would like to attach listeners -->
    <div id="soup">
        ...
           <palindrom-polymer></palindrom-polymer>
        ...
    </div>
</my-polymer-app>
<my-vue-app><!-- this is where you would like to attach listeners -->
    <div class="complatery different random soup">
        ...
           <palindrom-vue></palindrom-vue>
        ...
    </div>
</my-vue-app>

**Comment by warpech** [comment]
@tomalec I think that's a very clean solution. 

@alshakero will this suffice instead of the prefixes?

**Comment by alshakero** [comment]
@warpech IMHO yes it will.

**Comment by warpech** [comment]
Can this be closed?

**Comment by alshakero** [comment]
Yes.
